SRCDIR := $(shell pwd)
NAME := $(shell basename $(SRCDIR))
SRC := kpovmodeler-1.1.3.tar.gz
include ../common/Makefile
sources:
	[ -f $(SRC) ] || wget -O $(SRC) http://kpovmodeler.sourcearchive.com/downloads/5:1.1.3-kde4.1.2-0ubuntu1/kpovmodeler_1.1.3-kde4.1.2.orig.tar.gz