SRCDIR := $(shell pwd)
NAME := $(shell basename $(SRCDIR))
SRCFILE := kpovmodeler-1.1.3.tar.gz
DOWNLOAD := wget -O $(SRCFILE) http://kpovmodeler.sourcearchive.com/downloads/5:1.1.3-kde4.1.2-0ubuntu1/kpovmodeler_1.1.3-kde4.1.2.orig.tar.gz
include ../common/Makefile