#!/bin/bash

cmd=$1

which systemctl 1>/dev/null 2>&1
RETVAL=$?
[ $RETVAL -eq 0 ] && SYSTEMCTL=1 || SYSTEMCTL=0

function process() {
	local service=$1
	local cmd=$2
	local RETVAL=255
	
	echo -n "${cmd} ${service}"
	if [ $SYSTEMCTL -eq 1 ]
	then
		systemctl ${cmd} ${service}.service 1>/dev/null 2>&1
		RETVAL=$?
	else
		if [[ "${cmd}" == "enable" ]]
		then
			chkconfig ${service} on 1>/dev/null 2>&1
			RETVAL=$?
		elif [[ "${cmd}" == "disable" ]]
		then
			chkconfig ${service} off 1>/dev/null 2>&1
			RETVAL=$?
		else
			service ${service} ${cmd} 1>/dev/null 2>&1
			RETVAL=$?
		fi
	fi
	[ $RETVAL -eq 0 ] && echo '...Done.' || echo '...Failure'
	return $RETVAL
}

function process_all() {
	local cmd=$1
	echo "${cmd} all shinken element"
	echo
	process shinken-arbiter ${cmd}
	process shinken-broker ${cmd}
	process shinken-poller ${cmd}
	process shinken-reactionner ${cmd}
	process shinken-receiver ${cmd}
	process shinken-scheduler ${cmd}
	process shinken-skonf ${cmd}
}

function status() {
	if [ $SYSTEMCTL -eq 1 ]
	then
		systemctl status shinken-{arbiter,broker,poller,reactionner,receiver,scheduler,skonf}.service
	else
		service shinken-{arbiter,broker,poller,reactionner,receiver,scheduler,skonf}.service status
	fi
}

function admin() {
	echo "Get Status of all shinken element"
	echo
	echo -e "status\nquit" | shinken-admin | grep -v '^#' | grep -v 'Available functions'
}

function reload() {
	check
	local RETVAL=$?
	[ $RETVAL -eq 0 ] && process shinken-arbiter restart || exit 3
}

function check() {
	local RETVAL=3
	shinken-arbiter -v -c /etc/shinken/nagios.cfg -c /etc/shinken/shinken-specific.cfg
	local RETVAL=$?
	return $RETVAL
}

function usage() {
	echo "Usage: shinken [start|stop|restart|status|admin|enable|disable|reload|check]"
}

case $cmd in
	start)
		process_all start
		;;
	stop)
		process_all stop
		;;
	restart)
		process_all stop
		process_all start
		;;
	status)
		status
		;;
	admin)
		admin
		;;
	enable)
		process_all enable
		;;
	disable)
		process_all disable
		;;
	reload)
		reload
		;;
	check)
		check
		;;
	usage|help)
		usage
		;;
	*)
		echo Unknow syntax: $cmd
		usage
		exit 1
		;;
esac
exit 0
