SRCDIR := $(shell pwd)
NAME := $(shell basename $(SRCDIR))
SRC := fracplanet-0.4.0.tar.gz
include ../common/Makefile
sources:
	[ -f $(SRC) ] || wget -O $(SRC) http://sourceforge.net/projects/fracplanet/files/fracplanet/0.4.0/$(SRC)/download