SRCDIR := $(shell pwd)
NAME := $(shell basename $(SRCDIR))
SRCFILE := aluzzardi-pam_usb-0.5.0-25-g6a30dff.tar.gz
SRCURL := https://github.com/aluzzardi/pam_usb/tarball/master
include ../common/Makefile
